name: deploy-myst-site
on:
  push:
    branches: [main]
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g mystmd
      - run: myst build --html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html
      - id: deployment
        uses: actions/deploy-pages@v4
